[workspace]
resolver = "3"
members  = [ "nitro-cvv-gateway","nitro-cvv-host", "nitro-cvv-secret", "nitro-rs"]

[workspace.dependencies]
nix = { version = "0.30.1", features = ["net", "socket", "user"] }
